### ISSUE TITLE
Discord-Server

### ISSUE THREAD

**Issue by Phantonia** [Calador-t/ZeoHorror#1]
Ich hab zwar keine Ahnung, ob das irgendwie durchgezogen wird, aber ich hab Bock, und würde vorschlagen, sich über Discord zu vernetzen. Ich würde auch einen Server einrichten.

**Comment by Calador-t** [comment]
Können wir gerne machen Schreib mir die Adresse, dann Update ich die Read.Me :D

**Comment by Phantonia** [comment]
https://discord.gg/br96X35 ^^
Ich hab heute aber nicht mehr wirklich Zeit, den einzurichten, morgen kümmer ich mich aber gerne drum ^^

**Comment by Calador-t** [comment]
Cool danke bis jetzt sind wir eh noch nicht so viele also musst dich nicht stressen :D
